# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CD' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '4.0'
pod 'IQKeyboardManagerSwift', '4.0.6'
pod 'GoogleMaps', '2.1.0'
pod 'MBProgressHUD', '1.0.0'

end
